import { PrcssPageProps } from "@/lib/models/PrcssPageProps";

export const prcss: PrcssPageProps[] = [
  {
    id: "goddamn-internet",
    title: "The Goddamn Internet",
    year: 2018,
    height: 30,
    width: 40,
    description: "Incense",
    available: false,
    src: "/optimized/prcss/goddamn-internet.webp",
  },
  {
    id: "mushrooms-sketch",
    title: "Mushrooms sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "Mushrooms sketch",
    available: false,
    src: "/optimized/prcss/mushrooms-sketch.webp",
  },
  {
    id: "nom",
    title: "Nom Nom",
    year: 2018,
    height: 30,
    width: 40,
    description: "Nom Nom",
    available: false,
    src: "/optimized/prcss/nom.webp",
  },
  {
    id: "picnic-sketch",
    title: "Picnic sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "Picnic sketch",
    available: false,
    src: "/optimized/prcss/picnic-sketch.webp",
  },
  {
    id: "all-day-everyday",
    title: "All Day Everyday Forever",
    year: 2018,
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/optimized/prcss/all-day-everyday.webp",
  },
  {
    id: "abstract-sketch",
    title: "Abstract Sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/optimized/prcss/abstract-sketch.webp",
  },
  {
    id: "all-this-noise",
    title: "All This Noise",
    year: 2018,
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/optimized/prcss/all-this-noise.webp",
  },
  {
    id: "allday",
    title: "Allday",
    year: 2018,
    height: 30,
    width: 40,
    description: "Allday",
    available: false,
    src: "/optimized/prcss/allday.webp",
  },
  {
    id: "apple-pastel",
    title: "Apple Pastel",
    year: 2018,
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/optimized/prcss/apple-pastel.webp",
  },
  {
    id: "apple-sketch",
    title: "Apple Sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/optimized/prcss/apple-sketch.webp",
  },
  {
    id: "basket-apples-sketch",
    title: "Basket Apples Sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/optimized/prcss/basket-apples-sketch.webp",
  },
  {
    id: "basket-oranges-sketch",
    title: "Basket Oranges Sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/optimized/prcss/basket-oranges-sketch.webp",
  },
  {
    id: "blanket",
    title: "Blanket",
    year: 2018,
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/optimized/prcss/blanket.webp",
  },
  {
    id: "blue-fruit-sketch",
    title: "Blue Fruit",
    year: 2018,
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/optimized/prcss/blue-fruit-sketch.webp",
  },
  {
    id: "burning-down-the-house",
    title: "Burning Down The House",
    year: 2018,
    height: 30,
    width: 40,
    description: "Burning Down The House",
    available: false,
    src: "/optimized/prcss/burning-down-the-house.webp",
  },
  {
    id: "float",
    title: "Float",
    year: 2018,
    height: 30,
    width: 40,
    description: "Burning Down The House",
    available: false,
    src: "/optimized/prcss/float.webp",
  },
  {
    id: "incense",
    title: "Incense",
    year: 2018,
    height: 30,
    width: 40,
    description: "Incense",
    available: false,
    src: "/optimized/prcss/incense.webp",
  },
  {
    id: "flower-sketch",
    title: "Flower sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "Incense",
    available: false,
    src: "/optimized/prcss/flower-sketch.webp",
  },
  {
    id: "flower-sketching-abstract",
    title: "Flower sketch abstract",
    year: 2018,
    height: 30,
    width: 40,
    description: "Incense",
    available: false,
    src: "/optimized/prcss/flower-sketching-abstract.webp",
  },

  {
    id: "grit-teeth-sketch",
    title: "Grit Teeth Sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "Incense",
    available: false,
    src: "/optimized/prcss/grit-teeth-sketch.webp",
  },
  {
    id: "landscape",
    title: "Grit Teeth Sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "Incense",
    available: false,
    src: "/optimized/prcss/landscape.webp",
  },
  {
    id: "limit",
    title: "Limit",
    year: 2018,
    height: 30,
    width: 40,
    description: "Limt",
    available: false,
    src: "/optimized/prcss/limit.webp",
  },

  {
    id: "pharmacy-sketch",
    title: "Pharmacy sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "Pharmacy sketch",
    available: false,
    src: "/optimized/prcss/pharmacy-sketch.webp",
  },
  {
    id: "phone-sketch",
    title: "Phone sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "Pharmacy sketch",
    available: false,
    src: "/optimized/prcss/phone-sketch.webp",
  },

  {
    id: "pots-sketch",
    title: "Pots sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "Pots sketch",
    available: false,
    src: "/optimized/prcss/pots-sketch.webp",
  },
  {
    id: "random-plants-sketch",
    title: "Random Plants sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "Random Plants sketch",
    available: false,
    src: "/optimized/prcss/random-plants-sketch.webp",
  },
  {
    id: "real",
    title: "Real",
    year: 2018,
    height: 30,
    width: 40,
    description: "Real",
    available: false,
    src: "/optimized/prcss/real.webp",
  },
  {
    id: "smiles",
    title: "Smiles",
    year: 2018,
    height: 30,
    width: 40,
    description: "Smiles",
    available: false,
    src: "/optimized/prcss/smiles.webp",
  },
  {
    id: "the-end-pot-sketch",
    title: "The end pot sketch",
    year: 2018,
    height: 30,
    width: 40,
    description: "The end pot sketch",
    available: false,
    src: "/optimized/prcss/the-end-pot-sketch.webp",
  },
  {
    id: "the-end",
    title: "The end",
    year: 2018,
    height: 30,
    width: 40,
    description: "The end",
    available: false,
    src: "/optimized/prcss/the-end.webp",
  },
  {
    id: "three-get-gone",
    title: "Three Get Gone",
    year: 2018,
    height: 30,
    width: 40,
    description: "Three Get Gone",
    available: false,
    src: "/optimized/prcss/three-get-gone.webp",
  },
  {
    id: "tomato-orange",
    title: "Tomato Orange",
    year: 2018,
    height: 30,
    width: 40,
    description: "Tomato Orange",
    available: false,
    src: "/optimized/prcss/tomato-orange.webp",
  },
];
