import { ArtworkPageProps } from "../models/ArtworkPageProps";

export const works: ArtworkPageProps[] = [
  {
    id: "pears",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",
    height: 400,
    width: 400,
    description: "An abstract composition with vibrant colors.",
    available: false,
    src: "/pears.webp",
  },
  {
    id: "fingers-and-thumbs",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: false,
    src: "/fingers-&-thumbs.webp",
  },
  {
    id: "buddy",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/buddy.webp",
  },

  {
    id: "bonsai",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/IMG_3482.jpg",
  },
  {
    id: "26",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 400,
    width: 400,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/IMG_3172.jpg",
  },
  {
    id: "27",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/IMG_3168.jpg",
  },
  {
    id: "21",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 400,
    width: 400,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/IMG_3124.jpg",
  },
  {
    id: "vogue",
    title: "Vogue",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "vogue.jpg",
  },
  {
    id: "23",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/IMG_3135.jpg",
  },
  {
    id: "24",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/IMG_3150.jpg",
  },
  {
    id: "25",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/IMG_3153.jpg",
  },
  {
    id: "13",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/13.jpg",
  },
  {
    id: "28",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/23.jpg",
  },
  {
    id: "1",
    title: "Untitled",
    year: 2023,
    medium: "Oil on canvas",
    surface: "Canvas",
    height: 100,
    width: 80,
    description: "A beautiful abstract painting.",
    available: true,
    src: "/1.jpg",
  },
  {
    id: "2",
    title: "Sunset",
    year: 2022,
    medium: "Acrylic on canvas",
    surface: "Canvas",

    height: 120,
    width: 90,
    description: "A stunning sunset over the ocean.",
    available: false,
    src: "/2.jpg",
  },
  {
    id: "3",
    title: "Mountain Landscape",
    year: 2021,
    medium: "Watercolor on paper",
    surface: "Paper",

    height: 50,
    width: 70,
    description: "A serene mountain landscape.",
    available: true,
    src: "/3.jpg",
  },
  {
    id: "4",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/4.jpg",
  },

  {
    id: "5",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/5.jpg",
  },
  {
    id: "6",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/6.jpg",
  },
  {
    id: "7",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/7.jpg",
  },

  {
    id: "12",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/12.jpg",
  },

  {
    id: "14",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/14.jpg",
  },

  {
    id: "16",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 800,
    width: 600,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/16.jpg",
  },
  {
    id: "17",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 800,
    width: 600,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/17.jpg",
  },
  {
    id: "18",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 800,
    width: 600,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/18.jpg",
  },
  {
    id: "19",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 400,
    width: 400,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/19.jpg",
  },
  {
    id: "20",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 400,
    width: 400,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/20.jpg",
  },

  {
    id: "29",
    title: "Abstract Composition",
    year: 2020,
    medium: "Mixed media on canvas",
    surface: "Canvas",

    height: 80,
    width: 60,
    description: "An abstract composition with vibrant colors.",
    available: true,
    src: "/26.jpg",
  },
];
