import { ArtworkPageProps } from "../models/ArtworkPageProps";

export const works: ArtworkPageProps[] = [
  // 2025

  {
    id: "vogue",
    title: "Vogue",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas",
    height: 8,
    width: 10,
    description: "What, you never seen a voguing dandelion before?.",
    available: true,
    src: "/vogue.webp",
  },
  {
    id: "coffee-pot",
    title: "Canary Coffee Pot",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas",
    height: 15,
    width: 10,
    description: "A canary coffee pot.",
    available: true,
    src: "/coffee-pot.webp",
    tags: ["still-life"],
  },
  {
    id: "mushrooms",
    title: "Mushrooms",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 80,
    width: 60,
    description: "Mushrooms in a woodland maybe?",
    available: true,
    src: "/mushrooms.webp",
    tags: ["wildlife", "scene"],
  },
  {
    id: "mushroom-study",
    title: "Mushroom Study",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas",
    height: 8,
    width: 10,
    description: "Small study for a larger painting",
    available: true,
    src: "/mushroom-study.webp",
    tags: ["wildlife", "scene"],
  },

  {
    id: "pear",
    title: "Pear",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas",
    height: 8,
    width: 10,
    description: "A pair with a piercing",
    available: true,
    src: "/pear.webp",
    tags: ["fruit", "food"],
  },
  {
    id: "bow",
    title: "Bow",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas",
    height: 8,
    width: 10,
    description:
      "Saw a spider web with dew drops that I thought would look good with a bow on.",
    available: true,
    src: "/bow.webp",
  },
  {
    id: "apple",
    title: "Apple",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas",
    height: 8,
    width: 10,
    description: "Apple with a bum.",
    available: true,
    src: "/apple.webp",
  },

  // 2024

  {
    id: "picnic",
    title: "Picnic",
    year: 2024,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 40,
    width: 30,
    description: "A pretty spiritually loose picinic by the looks of things.",
    available: true,
    src: "/picnic.webp",
    tags: ["fruit", "food"],
  },

  {
    id: "pears",
    title: "Pears",
    year: 2024,
    medium: "Acrylic",
    surface: "Canvas",
    height: 400,
    width: 400,
    description: "Some pears folded over each other.",
    available: true,
    src: "/pears.webp",
  },

  //2023

  {
    id: "bonsai",
    title: "Bonsai",
    year: 2023,
    medium: "Acrylic",
    surface: "Canvas",
    height: 50,
    width: 40,
    description:
      "My father's now deceased bonsai, had it had a mid-life crisis.",
    available: true,
    src: "/bonsai.webp",
  },
  {
    id: "fingers-and-thumbs",
    title: "Fingers and Thumbs",
    year: 2023,
    medium: "Acrylic",
    surface: "Board",
    height: 30,
    width: 40,
    description:
      "It is like when you're a kid and you wrap a piece of string around your finger and it turns purple. But it's a peach.",
    available: true,
    src: "/fingers-and-thumbs.webp",
  },

  //2022

  //2021

  {
    id: "still-life-with-spring-flowers",
    title: "Still Life With Spring Flowers (after Thomas Hart Benton)",
    year: 2021,
    medium: "Acrylic",
    surface: "Canvas",
    height: 50,
    width: 40,
    description: "Reworking of a Thomas Hart Benton painting.",
    available: true,
    src: "/still-life-with-spring-flowers.webp",
  },
  {
    id: "apple-on-stone",
    title: "Apple on a Stone",
    year: 2021,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 400,
    width: 400,
    description: "Apple on stone with a flump based rainbow in the background.",
    available: true,
    src: "/apple-on-stone.webp",
  },

  {
    id: "are-we-having-fun-yet",
    title: "Are we having fun yet?",
    year: 2021,
    medium: "Acrylic",
    surface: "Canvas board",
    height: 400,
    width: 400,
    description: "Fun times with the tubes.",
    available: false,
    src: "/are-we-having-fun-yet.webp",
    tags: ["abstract"],
  },
  {
    id: "bauhaus-vase-2",
    title: "Bauhaus Vase II",
    year: 2021,
    medium: "Acrylic",
    surface: "Paper",
    height: 57,
    width: 35,
    description: "Bauhaus vase with fake flowers",
    available: true,
    src: "/bauhaus-vase-2.webp",
  },
  {
    id: "discs",
    title: "Discs",
    year: 2021,
    medium: "Acrylic",
    surface: "Paper",
    height: 42,
    width: 29.7,
    description: "Dics, Discs, Discs",
    available: true,
    src: "/discs.webp",
    tags: ["abstract"],
  },
  {
    id: "mapple",
    title: "Mmmmmmm'apple",
    year: 2021,
    medium: "Acrylic",
    surface: "Paper",
    height: 42,
    width: 29.7,
    description:
      "A twisted peeled apple resting utop 2 rocks. And some leaves. Don't forget the leaves.",
    available: true,
    src: "/mapple.webp",
    tags: ["fruit", "still-life"],
  },
  {
    id: "chaotic-neutral",
    title: "Bow",
    year: 2021,
    medium: "Acrylic",
    surface: "Paper",
    height: 42,
    width: 29.7,
    description: "Everything is proped up on itself, always.",
    available: true,
    src: "/chaotic-neutral.webp",
    tags: ["abstract"],
  },

  {
    id: "bauhaus-kettle",
    title: "Bauhaus Kettle",
    year: 2020,
    medium: "Acrylic",
    surface: "Canvas",
    height: 50,
    width: 40,
    description: "Bauhaus kettle with fake flowers",
    available: false,
    src: "/bauhaus-kettle.webp",
  },

  {
    id: "bauhaus-vase",
    title: "Bauhaus Vase",
    year: 2020,
    medium: "Acrylic",
    surface: "Paper",
    height: 42,
    width: 29.7,
    description: "Bauhaus vase with fake flowers",
    available: true,
    src: "/bauhaus-vase.webp",
  },
  {
    id: "better-distraction-1",
    title: "A Better Distraction",
    year: 2020,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 25,
    width: 25,
    description: "A very focussed funnel",
    available: true,
    src: "/better-distraction-1.webp",
  },
  {
    id: "better-distraction-2",
    title: "A Better Distraction II",
    year: 2020,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 25,
    width: 25,
    description: "Another very focussed funnel",
    available: true,
    src: "/better-distraction-2.webp",
  },

  {
    additional:
      "This piece of part of the The Contraband Collection's continuously migrating exhibitions and workshops.",
    id: "down-the-hill-from-the-swing",
    title: "The Place Down the Hill from the Swing",
    year: 2019,
    medium: "Acrylic",
    surface: "Linen",
    height: 40,
    width: 30,
    description:
      "An almagamation of landscapes from various parts of South America.",
    available: true,
    src: "/down-the-hill-from-the-swing.webp",
    tags: ["abstract", "landscape"],
  },
  {
    id: "fictional-flowers-1",
    title: "Fictional Flowers",
    year: 2018,
    medium: "Acrylic",
    surface: "Paper",
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/fictional-flowers-1.webp",
    tags: ["abstract", "still-life"],
  },
  {
    id: "fictional-flowers-2",
    title: "Fictional Flowers",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/fictional-flowers-2.webp",
    tags: ["abstract", "still-life"],
  },
  {
    id: "fictional-flowers-3",
    title: "Fictional Flowers",
    year: 2019,
    medium: "Acrylic",
    surface: "Canvas",
    height: 50,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/fictional-flowers-3.webp",
    tags: ["abstract", "still-life"],
  },
  {
    id: "fictional-flowers-4",
    title: "Fictional Flowers",
    year: 2025,
    medium: "Acrylic",
    surface: "Paper",
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: true,
    src: "/fictional-flowers-4.webp",
    tags: ["abstract", "still-life"],
  },

  {
    id: "ghibli-rock",
    title: "Ghibli Rock",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 30,
    width: 40,
    description:
      "Inspired by the time I went to a late night screening of Princess Mononoke and fell asleep in the cinema.",
    available: false,
    src: "/ghibli-rock.webp",
  },
  {
    id: "gummy-bear-1",
    title: "Gummy Bear",
    year: 2020,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 25,
    width: 25,
    description: "Nice gelatinuos forms, moving all over each other.",
    available: true,
    src: "/gummy-bear-1.webp",
    tags: ["abstract"],
  },

  {
    id: "grit-teeth",
    title: "GRIT TEETH",
    year: 2018,
    medium: "Acrylic and Ink",
    surface: "Paper",
    height: 30,
    width: 40,
    description: "A load of contrast fighting it out.",
    available: true,
    src: "/grit-teeth.webp",
    tags: ["abstract"],
  },
  {
    id: "hotdog",
    title: "Hotdog",
    year: 2021,
    medium: "Acrylic",
    surface: "Canvas",
    height: 25,
    width: 25,
    description: "Tubular forms and bright colours.",
    available: true,
    src: "/hotdog.webp",
    tags: ["abstract"],
  },
  {
    id: "i-wish-douglas-was-still-here",
    title: "I wish Douglas Was Still Here",
    year: 2019,
    medium: "Acrylic",
    surface: "Canvas",
    height: 80,
    width: 50,
    description: "Tubular forms and bright colours.",
    available: true,
    src: "/i-wish-douglas-was-still-here.webp",
    additional:
      "Painted as part of the residency between The Latch & The Contraband Collective",
    tags: ["abstract"],
  },
  {
    id: "isabella-island",
    title: "Isabella Island",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 59.4,
    width: 29.7,
    description:
      "Based around the colours of the volcanic island of Isabella in the Galapagos.",
    available: false,
    src: "/isabella-island.webp",
    tags: ["abstract", "landscape"],
  },
  {
    id: "laguna-loops",
    title: "Laguna Loops",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 30,
    width: 40,
    description: "When you're up, you're up.",
    available: true,
    src: "/laguna-loops.webp",
    tags: ["abstract", "landscape"],
  },
  {
    id: "land-and-sea",
    title: "Land & Sea",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 30,
    width: 40,
    description: "The horizon and the land and the sky.",
    available: false,
    src: "/land-and-sea.webp",
    tags: ["abstract", "landscape"],
  },

  {
    id: "memphis-parthenon",
    title: "Memphis Parthenon",
    year: 2022,
    medium: "Acrylic",
    surface: "Paper",
    height: 42,
    width: 29.7,
    description:
      "An homage to the Memphis Group and all their spectacularly tacky homewares.",
    available: true,
    src: "/memphis-parthenon.webp",
    tags: ["abstract"],
  },

  {
    id: "out-of-the-fire",
    title: "Out of the Fire",
    year: 2025,
    medium: "Acrylic",
    surface: "Paper",
    height: 40,
    width: 30,
    description: "A small window in the bedlam of chaos.",
    available: true,
    src: "/out-of-the-fire.webp",
    tags: ["abstract"],
  },

  {
    id: "portal",
    title: "Portal",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 40,
    width: 30,
    description: "Spiral spirals",
    available: false,
    src: "/portal.webp",
    tags: ["fruit", "food"],
  },
  {
    id: "wet-fruit",
    title: "Wet Fruit",
    year: 2021,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 30,
    width: 40,
    description:
      "It is like when you're a kid and you wrap a piece of string around your finger and it turns purple. But it's a peach.",
    available: true,
    src: "/wet-fruit.webp",
  },
];
