import { ArtworkPageProps } from "@/lib/models/ArtworkPageProps";

export const works2019: ArtworkPageProps[] = [
  {
    id: "space-lectern-1",
    title: "Space Lectern",
    year: 2019,
    medium: "Wood, Plaser, Expanding Foam, Rubber, Emulsion, Acrylic",
    surface: "",
    height: 42,
    width: 29.7,
    description:
      "A lectern for the Space Pope. Fulfilling the idea of space age religion and wonder.",
    available: false,
    src: "/works/space-lectern-1.webp",
    tags: ["sculpture"],
    linked: [
      {
        id: "space-lectern-4",
        title: "Space Lectern",
        year: 2019,
        medium: "Wood, Plaser, Expanding Foam, Rubber, Emulsion, Acrylic",
        surface: "",
        height: 42,
        width: 29.7,
        description:
          "A lectern for the Space Pope. Fulfilling the idea of space age religion and wonder.",
        available: false,
        src: "/works/space-lectern-4.webp",
      },
      {
        id: "space-lectern-3",
        title: "Space Lectern",
        year: 2019,
        medium: "Wood, Plaser, Expanding Foam, Rubber, Emulsion, Acrylic",
        surface: "",
        height: 42,
        width: 29.7,
        description:
          "A lectern for the Space Pope. Fulfilling the idea of space age religion and wonder.",
        available: false,
        src: "/works/space-lectern-3.webp",
      },
    ],
    additional:
      "Created as part of the residency between The Latch & The Contraband Collective",
  },
  {
    id: "i-wish-douglas-was-still-here",
    title: "I wish Douglas Was Still Here",
    year: 2019,
    medium: "Acrylic",
    surface: "Canvas",
    height: 80,
    width: 50,
    description: "Tubular forms and bright colours.",
    available: true,
    src: "/works/i-wish-douglas-was-still-here.webp",
    additional:
      "Painted as part of the residency between The Latch & The Contraband Collective",
    tags: ["abstract"],
  },
  {
    id: "isabella-island",
    title: "Isabella Island",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 59.4,
    width: 29.7,
    description:
      "Based around the colours of the volcanic island of Isabella in the Galapagos.",
    available: false,
    src: "/works/isabella-island.webp",
    tags: ["abstract", "landscape"],
  },
  {
    id: "laguna-loops",
    title: "Laguna Loops",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 30,
    width: 40,
    description: "When you're up, you're up.",
    available: true,
    src: "/works/laguna-loops.webp",
    tags: ["abstract", "landscape"],
  },
  {
    id: "land-and-sea",
    title: "Land & Sea",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 30,
    width: 40,
    description: "The horizon and the land and the sky.",
    available: false,
    src: "/works/land-and-sea.webp",
    tags: ["abstract", "landscape"],
  },
  {
    id: "summer",
    title: "Its Almost Summer Around the Corner",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 60,
    width: 41,
    description: "It's always almost summer somewhere.",
    available: true,
    src: "/works/summer.webp",
    tags: ["landscape", "abstract"],
  },
  {
    id: "tiger",
    title: "Tiger",
    year: 2019,
    medium: "Acrylic and Ink",
    surface: "Paper",
    height: 77,
    width: 56,
    description: "What do you call a tiger with no eyes?",
    available: true,
    src: "/works/tiger.webp",
    tags: ["landscape"],
  },

  {
    id: "toothpaste",
    title: "Toothpaste",
    year: 2019,
    medium: "Acrylic and Ink",
    surface: "Paper",
    height: 77,
    width: 50,
    description: "Smooth and silky, but pasty and soft.",
    available: true,
    src: "/works/toothpaste.webp",
    tags: ["abstract"],
  },
  {
    additional:
      "This piece of part of the The Contraband Collection's continuously migrating exhibitions and workshops.",
    id: "down-the-hill-from-the-swing",
    title: "The Place Down the Hill from the Swing",
    year: 2019,
    medium: "Acrylic",
    surface: "Linen",
    height: 40,
    width: 30,
    description:
      "An almagamation of landscapes from various parts of South America.",
    available: true,
    src: "/works/down-the-hill-from-the-swing.webp",
    tags: ["abstract", "landscape"],
  },

  {
    id: "fictional-flowers-2",
    title: "Fictional Flowers",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/works/fictional-flowers-2.webp",
    tags: ["abstract", "still-life"],
  },
  {
    id: "fictional-flowers-3",
    title: "Fictional Flowers",
    year: 2019,
    medium: "Acrylic",
    surface: "Canvas",
    height: 50,
    width: 40,
    description: "A bunch of fictional flowers",
    available: false,
    src: "/works/fictional-flowers-3.webp",
    tags: ["abstract", "still-life"],
  },

  {
    id: "ghibli-rock",
    title: "Ghibli Rock",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 30,
    width: 40,
    description:
      "Inspired by the time I went to a late night screening of Princess Mononoke and fell asleep in the cinema.",
    available: false,
    src: "/works/ghibli-rock.webp",
  },
  {
    id: "portal",
    title: "Portal",
    year: 2019,
    medium: "Acrylic",
    surface: "Paper",
    height: 40,
    width: 30,
    description: "Spiral spirals",
    available: false,
    src: "/works/portal.webp",
    tags: ["fruit", "food"],
  },
];
