import { ArtworkPageProps } from "@/lib/models/ArtworkPageProps";

export const works2020: ArtworkPageProps[] = [
  {
    id: "bauhaus-kettle",
    title: "Bauhaus Kettle",
    year: 2020,
    medium: "Acrylic",
    surface: "Canvas",
    height: 50,
    width: 40,
    description: "Bauhaus kettle with fake flowers",
    available: false,
    src: "/optimized/works/bauhaus-kettle.webp",
  },
  {
    id: "gummy-bear-1",
    title: "Gummy Bear",
    year: 2020,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 25,
    width: 25,
    description: "Nice gelatinuos forms, moving all over each other.",
    available: true,
    src: "/optimized/works/gummy-bear-1.webp",
    tags: ["abstract"],
  },
  {
    id: "out-of-the-fire",
    title: "Out of the Fire",
    year: 2020,
    medium: "Acrylic",
    surface: "Paper",
    height: 50,
    width: 35,
    description: "A small window in the bedlam of chaos.",
    available: true,
    src: "/optimized/works/out-of-the-fire.webp",
    tags: ["abstract"],
  },
  {
    id: "bauhaus-vase",
    title: "Bauhaus Vase",
    year: 2020,
    medium: "Acrylic",
    surface: "Paper",
    height: 42,
    width: 29.7,
    description: "Bauhaus vase with fake flowers",
    available: true,
    src: "/optimized/works/bauhaus-vase.webp",
  },
  {
    id: "better-distraction-1",
    title: "A Better Distraction",
    year: 2020,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 25,
    width: 25,
    description: "A very focussed funnel",
    available: true,
    src: "/optimized/works/better-distraction-1.webp",
  },
  {
    id: "better-distraction-2",
    title: "A Better Distraction II",
    year: 2020,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 25,
    width: 25,
    description: "Another very focussed funnel",
    available: true,
    src: "/optimized/works/better-distraction-2.webp",
  },
];
