import { ArtworkPageProps } from "@/lib/models/ArtworkPageProps";

export const works2021: ArtworkPageProps[] = [
  {
    id: "still-life-with-spring-flowers",
    title: "Still Life With Spring Flowers (after Thomas Hart Benton)",
    year: 2021,
    medium: "Acrylic",
    surface: "Canvas",
    height: 50,
    width: 40,
    description: "Reworking of a Thomas Hart Benton painting.",
    available: true,
    src: "/still-life-with-spring-flowers.webp",
  },
  {
    id: "untitled",
    title: "Untitled",
    year: 2021,
    medium: "Acrylic",
    surface: "Canvas",
    height: 50,
    width: 40,
    description:
      "What you get when you're looking at infrared heat map images alot.",
    available: true,
    src: "/untitled.webp",
    tags: ["abstract"],
  },
  {
    id: "apple-on-stone",
    title: "Apple on a Stone",
    year: 2021,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 400,
    width: 400,
    description: "Apple on stone with a flump based rainbow in the background.",
    available: true,
    src: "/apple-on-stone.webp",
  },

  {
    id: "are-we-having-fun-yet",
    title: "Are we having fun yet?",
    year: 2021,
    medium: "Acrylic",
    surface: "Canvas board",
    height: 400,
    width: 400,
    description: "Fun times with the tubes.",
    available: false,
    src: "/are-we-having-fun-yet.webp",
    tags: ["abstract"],
  },
  {
    id: "wet-fruit",
    title: "Wet Fruit",
    year: 2021,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 30,
    width: 40,
    description:
      "It is like when you're a kid and you wrap a piece of string around your finger and it turns purple. But it's a peach.",
    available: true,
    src: "/wet-fruit.webp",
  },
  {
    id: "hotdog",
    title: "Hotdog",
    year: 2021,
    medium: "Acrylic",
    surface: "Canvas",
    height: 25,
    width: 25,
    description: "Tubular forms and bright colours.",
    available: true,
    src: "/hotdog.webp",
    tags: ["abstract"],
  },

  {
    id: "raspberry",
    title: "Pppppptthhhhttt",
    year: 2021,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 25,
    width: 25,
    description: "Blowing'em raspberries",
    available: true,
    src: "/raspberry.webp",
    tags: ["fruit", "still-life"],
  },
  {
    id: "bauhaus-vase-2",
    title: "Bauhaus Vase II",
    year: 2021,
    medium: "Acrylic",
    surface: "Paper",
    height: 57,
    width: 35,
    description: "Bauhaus vase with fake flowers",
    available: true,
    src: "/bauhaus-vase-2.webp",
  },
  {
    id: "discs",
    title: "Discs",
    year: 2021,
    medium: "Acrylic",
    surface: "Paper",
    height: 42,
    width: 29.7,
    description: "Dics, Discs, Discs",
    available: true,
    src: "/discs.webp",
    tags: ["abstract"],
  },
  {
    id: "mapple",
    title: "Mmmmmmm'apple",
    year: 2021,
    medium: "Acrylic",
    surface: "Paper",
    height: 42,
    width: 29.7,
    description:
      "A twisted peeled apple resting utop 2 rocks. And some leaves. Don't forget the leaves.",
    available: true,
    src: "/mapple.webp",
    tags: ["fruit", "still-life"],
  },
  {
    id: "chaotic-neutral",
    title: "Bow",
    year: 2021,
    medium: "Acrylic",
    surface: "Paper",
    height: 42,
    width: 29.7,
    description: "Everything is proped up on itself, always.",
    available: true,
    src: "/chaotic-neutral.webp",
    tags: ["abstract"],
  },
];
