import { ArtworkPageProps } from "@/lib/models/ArtworkPageProps";

export const works2025: ArtworkPageProps[] = [
  {
    id: "mushrooms",
    title: "Mushrooms",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas Board",
    height: 75,
    width: 60,
    description: "Mushrooms in a woodland maybe?",
    available: true,
    src: "/works/mushrooms.webp",
    tags: ["wildlife", "scene"],
  },
  {
    id: "vogue",
    title: "Vogue",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas",
    height: 20,
    width: 15,
    description: "What, you never seen a voguing dandelion before?.",
    available: true,
    src: "/works/vogue.webp",
  },
  {
    id: "coffee-pot",
    title: "Canary Coffee Pot",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas",
    height: 25,
    width: 20,
    description: "A canary coffee pot.",
    available: true,
    src: "/works/coffee-pot.webp",
    tags: ["still-life"],
  },
  {
    id: "fictional-flowers-4",
    title: "Fictional Flowers",
    year: 2025,
    medium: "Acrylic",
    surface: "Paper",
    height: 30,
    width: 40,
    description: "A bunch of fictional flowers",
    available: true,
    src: "/works/fictional-flowers-4.webp",
    tags: ["abstract", "still-life"],
  },

  {
    id: "woods",
    title: "The Woods",
    year: 2025,
    medium: "Acrylic",
    surface: "Paper",
    height: 42,
    width: 29.7,
    description:
      "A small woodland scene with a few trees and total disregard for perspective.",
    available: true,
    src: "/works/woods.webp",
  },
  {
    id: "pear",
    title: "Pear",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas",
    height: 20,
    width: 15,
    description: "A pair with a piercing",
    available: true,
    src: "/works/pear.webp",
    tags: ["fruit", "food"],
  },
  {
    id: "bow",
    title: "Bow",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas",
    height: 20,
    width: 15,
    description:
      "Saw a spider web with dew drops that I thought would look good with a bow on.",
    available: true,
    src: "/works/bow.webp",
  },
  {
    id: "apple",
    title: "Apple",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas",
    height: 25,
    width: 20,
    description: "Apple with a bum.",
    available: true,
    src: "/works/apple.webp",
  },
  {
    id: "mushroom-study",
    title: "Mushroom Study",
    year: 2025,
    medium: "Acrylic",
    surface: "Canvas",
    height: 20,
    width: 15,
    description: "Small study for a larger painting",
    available: true,
    src: "/works/mushroom-study.webp",
    tags: ["wildlife", "scene"],
  },
];
